name: Build

on:
  pull_request:
  push:
    tags:
    - '*'
    branches:
    - main

# disable concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14, macos-13]

    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: build
      if: runner.os != 'Windows'
      run: cd build && make

    - if: runner.os == 'Windows'
      run: cd build && cmake --build "."