name: Build

on:
  pull_request:
  push:
    tags:
    - '*'
    branches:
    - main

# disable concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14, macos-13]

    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up conda environment to install Boost
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        auto-update-conda: true
        activate-environment: conda-env
      if: runner.os == 'Windows' || runner.os == 'Linux'

    - name: Install Boost
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew upgrade
        brew install boost
    - if: runner.os != 'macOS'
      shell: bash
      run: |
        conda install -c conda-forge boost

    - name: ubuntu packages
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y xorg-dev libglu1-mesa-dev xpra xserver-xorg-video-dummy freeglut3-dev

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5

    - name: build
      if: runner.os != 'Windows'
      run: cd build && make

    - if: runner.os == 'Windows'
      run: cd build && cmake --build "."